version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: socialapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socialapp-api
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/socialapp?sslmode=disable
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 8080
      ENVIRONMENT: production
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
